In [1]:
!pip install transformers

In [2]:
import torch

In [3]:
from transformers import BertTokenizer, BertModel

In [4]:
import random

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
random_seed=42

In [7]:
random.seed(random_seed)

In [8]:
torch.manual_seed(random_seed)

In [9]:
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(random_seed)

In [10]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"), '(Request ID: 3b9bae5f-fa4e-497a-8c5d-c2cf4a18ad13)')

In [ ]:
model=BertModel.from_pretrained("bert-base-uncased")

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [ ]:
text="ineuron is for the best AI Courses."

In [ ]:
encoding=tokenizer.batch_encode_plus([text],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [ ]:
input_ids=encoding["input_ids"]

In [ ]:
input_ids

tensor([[  101,  1999, 11236,  2239,  2003,  2005,  1996,  2190,  9932,  5352,
          1012,   102]])

In [ ]:
attention_mask=encoding["attention_mask"]

In [ ]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
with torch.no_grad():
  outputs=model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [ ]:
word_embeddings.shape

torch.Size([1, 12, 768])

In [ ]:
word_embeddings

tensor([[[-0.4271, -0.1666,  0.1909,  ..., -0.2987,  0.6356,  0.6963],
         [-0.4555, -0.5843,  0.3312,  ..., -0.1475,  0.5605,  1.2290],
         [-0.7174, -0.4126,  1.0531,  ...,  0.3063,  0.3983,  0.2660],
         ...,
         [ 0.3224,  0.1035,  0.5626,  ..., -0.2507, -0.0866, -0.3084],
         [ 0.5164,  0.1578, -0.0727,  ...,  0.2103, -0.4651, -0.2494],
         [ 0.2963,  0.2963,  0.2604,  ...,  0.3185, -0.6820, -0.1199]]])

In [ ]:
input_ids[0]

tensor([  101,  1999, 11236,  2239,  2003,  2005,  1996,  2190,  9932,  5352,
         1012,   102])

In [ ]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [ ]:
decode

'ineuron is for the best ai courses.'